# Copyright (c) 2019, UK HealthCare (https://ukhealthcare.uky.edu) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: drupal-dev-composer-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-dev-composer-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: drupal-dev-composer-storage-class
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/default/drupal-dev/composer"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: drupal-dev-config-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-dev-config-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: drupal-dev-config-storage-class
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/default/drupal-dev/docroot/config"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: drupal-dev-modules-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-dev-modules-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: drupal-dev-modules-storage-class
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/default/drupal-dev/docroot/modules"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: drupal-dev-themes-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-dev-themes-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: drupal-dev-themes-storage-class
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/default/drupal-dev/docroot/themes"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: drupal-dev-sites-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: drupal-dev-sites-persistent-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: drupal-dev-sites-storage-class
  hostPath:
    path: "/Users/Shared/Kubernetes/persistent-volumes/default/drupal-dev/docroot/sites"

---