# Copyright (c) 2019, UK HealthCare (https://ukhealthcare.uky.edu) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##########################


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-dev-composer-pv-claim
  labels:
    app: drupal-dev
spec:
  storageClassName: drupal-dev-composer-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-dev-config-pv-claim
  labels:
    app: drupal-dev
spec:
  storageClassName: drupal-dev-config-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-dev-modules-pv-claim
  labels:
    app: drupal-dev
spec:
  storageClassName: drupal-dev-modules-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-dev-themes-pv-claim
  labels:
    app: drupal-dev
spec:
  storageClassName: drupal-dev-themes-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-dev-sites-pv-claim
  labels:
    app: drupal-dev
spec:
  storageClassName: drupal-dev-sites-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
   
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-dev-php-config
data:
  drupal-php.ini: |
    ;add php config here

---

apiVersion: v1
kind: Service
metadata:
  name: drupal-dev
  labels:
    app: drupal-dev
spec:
  ports:
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: drupal-dev
  type: LoadBalancer
  
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drupal-dev
  labels:
    app: drupal-dev
spec:
  selector:
    matchLabels:
      app: drupal-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal-dev
    spec:
      containers:
      - image: internal/drupal-dev:8.7.6-v1
        name: drupal-dev
        env:
        - name: MYSQL_DATABASE
          value: mariadb
        - name: MEDIAWIKI_DATABASE_NAME
          value: mediawiki
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-secret
              key: password
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 3 
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: drupal-dev-php-config
          mountPath: /usr/local/etc/php/conf.d/drupal-php.ini
          subPath: drupal-php.ini
#composer-persistent-storage#        - name: drupal-dev-composer-persistent-storage
#composer-persistent-storage#          mountPath: /var/www/composer
#config-persistent-storage#        - name: drupal-dev-config-persistent-storage
#config-persistent-storage#          mountPath: /var/www/docroot/config
#modules-persistent-storage#        - name: drupal-dev-modules-persistent-storage
#modules-persistent-storage#          mountPath: /var/www/docroot/modules/custom
#themes-persistent-storage#        - name: drupal-dev-themes-persistent-storage
#themes-persistent-storage#          mountPath: /var/www/docroot/themes/custom
#sites-persistent-storage#        - name: drupal-dev-sites-persistent-storage
#sites-persistent-storage#          mountPath: /var/www/docroot/sites/default
      volumes:
        - name: drupal-dev-php-config
          configMap:
            name: drupal-dev-php-config
#composer-persistent-storage#        - name: drupal-dev-composer-persistent-storage
#composer-persistent-storage#          persistentVolumeClaim:
#composer-persistent-storage#            claimName: drupal-dev-composer-pv-claim
#config-persistent-storage#        - name: drupal-dev-config-persistent-storage
#config-persistent-storage#          persistentVolumeClaim:
#config-persistent-storage#            claimName: drupal-dev-config-pv-claim
#modules-persistent-storage#        - name: drupal-dev-modules-persistent-storage
#modules-persistent-storage#          persistentVolumeClaim:
#modules-persistent-storage#            claimName: drupal-dev-modules-pv-claim
#themes-persistent-storage#        - name: drupal-dev-themes-persistent-storage
#themes-persistent-storage#          persistentVolumeClaim:
#themes-persistent-storage#            claimName: drupal-dev-themes-pv-claim
#sites-persistent-storage#        - name: drupal-dev-sites-persistent-storage
#sites-persistent-storage#          persistentVolumeClaim:
#sites-persistent-storage#            claimName: drupal-dev-sites-pv-claim